using System.Collections.Generic;
using System.Windows.Media;

namespace OTTD_Cargo_Payment.CargoDefinitions {
    public static class DefaultDefinitions {
        public static List<CargoScheme> Defaults = new List<CargoScheme> {
                new CargoScheme {
                    SchemeName = "ECS Vectors 2012", IsDefault = true,
                    CargoDefinitions = new List<CargoDefinition> {
                        new PerishableCargoDefinition {
                            ItemID = 0,
                            TypeName = "Passengers",
                            CargoLabel = "PASS",
                            PriceFactor = 100,
                            Color = Colors.DarkGray,
                            CargoSprite = "0x10C9",
                            CargoIcon = "",
                            MaxDistance = 4000,
                            DiminishingReturnsLinearity = 1000,
                            PrimaryDropoffCurveOffset = 4,
                            PrimaryDropoffCurveShortDistanceAdjustment = 7,
                            PrimaryDropoffCurveShortDistanceEnd = 300,
                            PrimaryDropoffCurveMediumDistanceAdjustment = 16,
                            PrimaryDropoffCurveMediumDistanceStart = 300,
                            PrimaryDropoffCurveMediumDistanceEnd = 500,
                            PrimaryDropoffCurveLongDistanceAdjustment = -17,
                            PrimaryDropoffCurveLongDistanceStart = 500,
                            PrimaryDropoffCurveLongDistanceEnd = 1000,
                            PrimaryDropoffCurveLongevity = 500,
                            PrimaryDropoffCurveLongevityAdjustment = 10,
                            SecondaryReturnDivisor = 4,
                            FinalReturnDivisor = 16,
                            SecondaryDropoffCurveOffset = 150,
                            SecondaryDropoffCurveDistanceAdjustment = -13,
                            SecondaryDropoffCurveLongevity = 150,
                            SecondaryDropoffCurveLongevityAdjustment = 10,
                        },
                        new BulkCargoDefinition {
                            ItemID = 1,
                            TypeName = "Coal",
                            CargoLabel = "COAL",
                            PriceFactor = 60,
                            Color = Colors.Black,
                            CargoSprite = "0x10CA",
                            CargoIcon = "",
                            MaxDistance = 4000,
                            DiminishingReturnsLinearity = 1000,
                            MaxDeliveryTime = 256,
                            LateCargoDivider = 1,
                        },
                        new BulkCargoDefinition {
                            ItemID = 2,
                            TypeName = "Mail",
                            CargoLabel = "MAIL",
                            PriceFactor = 150,
                            Color = Colors.White,
                            CargoSprite = "0x10CB",
                            CargoIcon = "",
                            MaxDistance = 4000,
                            DiminishingReturnsLinearity = 1000,
                            MaxDeliveryTime = 240,
                            LateCargoDivider = 6,
                        },
                        new BulkCargoDefinition {
                            ItemID = 3,
                            TypeName = "Oil",
                            CargoLabel = "OIL_",
                            PriceFactor = 75,
                            Color = Colors.MediumPurple,
                            CargoSprite = "0x10CC",
                            CargoIcon = "",
                            MaxDistance = 4000,
                            DiminishingReturnsLinearity = 1000,
                            MaxDeliveryTime = 256,
                            LateCargoDivider = 1,
                        },
                        new PerishableCargoDefinition {
                            ItemID = 4,
                            TypeName = "Livestock",
                            CargoLabel = "LVST",
                            PriceFactor = 80,
                            Color = Colors.YellowGreen,
                            CargoSprite = "0x10CD",
                            CargoIcon = "",
                            MaxDistance = 2000,
                            DiminishingReturnsLinearity = 1000,
                            PrimaryDropoffCurveOffset = 30,
                            PrimaryDropoffCurveShortDistanceAdjustment = 7,
                            PrimaryDropoffCurveShortDistanceEnd = 300,
                            PrimaryDropoffCurveMediumDistanceAdjustment = 16,
                            PrimaryDropoffCurveMediumDistanceStart = 300,
                            PrimaryDropoffCurveMediumDistanceEnd = 500,
                            PrimaryDropoffCurveLongDistanceAdjustment = -8,
                            PrimaryDropoffCurveLongDistanceStart = 500,
                            PrimaryDropoffCurveLongDistanceEnd = 1000,
                            PrimaryDropoffCurveLongevity = 500,
                            PrimaryDropoffCurveLongevityAdjustment = 10,
                            SecondaryReturnDivisor = 3,
                            FinalReturnDivisor = 20,
                            SecondaryDropoffCurveOffset = 255,
                            SecondaryDropoffCurveDistanceAdjustment = -8,
                            SecondaryDropoffCurveLongevity = 150,
                            SecondaryDropoffCurveLongevityAdjustment = 10,
                        },
                        new BulkCargoDefinition {
                            ItemID = 5,
                            TypeName = "Goods",
                            CargoLabel = "GOOD",
                            PriceFactor = 125,
                            Color = Colors.DarkGray,
                            CargoSprite = "0x10CE",
                            CargoIcon = "",
                            MaxDistance = 4000,
                            DiminishingReturnsLinearity = 1000,
                            MaxDeliveryTime = 240,
                            LateCargoDivider = 6,
                        },
                        new PerishableCargoDefinition {
                            ItemID = 6,
                            TypeName = "Cereals",
                            CargoLabel = "CERE",
                            PriceFactor = 73,
                            Color = Colors.Orange,
                            CargoSprite = "0x10CF",
                            CargoIcon = "",
                            MaxDistance = 4000,
                            DiminishingReturnsLinearity = 1000,
                            PrimaryDropoffCurveOffset = 125,
                            PrimaryDropoffCurveShortDistanceAdjustment = -500,
                            PrimaryDropoffCurveShortDistanceEnd = 4000,
                            PrimaryDropoffCurveMediumDistanceAdjustment = 4000,
                            PrimaryDropoffCurveMediumDistanceStart = 4000,
                            PrimaryDropoffCurveMediumDistanceEnd = 4000,
                            PrimaryDropoffCurveLongDistanceAdjustment = 4000,
                            PrimaryDropoffCurveLongDistanceStart = 4000,
                            PrimaryDropoffCurveLongDistanceEnd = 4000,
                            PrimaryDropoffCurveLongevity = 1500,
                            PrimaryDropoffCurveLongevityAdjustment = -1,
                            SecondaryReturnDivisor = 100,
                            FinalReturnDivisor = 500,
                            SecondaryDropoffCurveOffset = 0,
                            SecondaryDropoffCurveDistanceAdjustment = 4000,
                            SecondaryDropoffCurveLongevity = 150,
                            SecondaryDropoffCurveLongevityAdjustment = 4000,
                        },
                        new BulkCargoDefinition {
                            ItemID = 7,
                            TypeName = "Wood",
                            CargoLabel = "WOOD",
                            PriceFactor = 70,
                            Color = Colors.ForestGreen,
                            CargoSprite = "0x10D0",
                            CargoIcon = "",
                            MaxDistance = 4000,
                            DiminishingReturnsLinearity = 1000,
                            MaxDeliveryTime = 256,
                            LateCargoDivider = 1,
                        },
                        new BulkCargoDefinition {
                            ItemID = 8,
                            TypeName = "Iron ore",
                            CargoLabel = "IORE",
                            PriceFactor = 65,
                            Color = Colors.OrangeRed,
                            CargoSprite = "0x10D1",
                            CargoIcon = "",
                            MaxDistance = 4000,
                            DiminishingReturnsLinearity = 1000,
                            MaxDeliveryTime = 256,
                            LateCargoDivider = 1,
                        },
                        new BulkCargoDefinition {
                            ItemID = 9,
                            TypeName = "Steel",
                            CargoLabel = "STEL",
                            PriceFactor = 80,
                            Color = Colors.Red,
                            CargoSprite = "0x10D2",
                            CargoIcon = "",
                            MaxDistance = 4000,
                            DiminishingReturnsLinearity = 1000,
                            MaxDeliveryTime = 256,
                            LateCargoDivider = 1,
                        },
                        new BulkCargoDefinition {
                            ItemID = 10,
                            TypeName = "Gold",
                            CargoLabel = "GOLD",
                            PriceFactor = 110,
                            Color = Colors.CornflowerBlue,
                            CargoSprite = "0x10D3",
                            CargoIcon = "",
                            MaxDistance = 4000,
                            DiminishingReturnsLinearity = 1000,
                            MaxDeliveryTime = 256,
                            LateCargoDivider = 1,
                        },
                        new PerishableCargoDefinition {
                            ItemID = 11,
                            TypeName = "Food",
                            CargoLabel = "FOOD",
                            PriceFactor = 87,
                            Color = Colors.Yellow,
                            CargoSprite = "0x10D8",
                            CargoIcon = "",
                            MaxDistance = 4000,
                            DiminishingReturnsLinearity = 1000,
                            PrimaryDropoffCurveOffset = 100,
                            PrimaryDropoffCurveShortDistanceAdjustment = -500,
                            PrimaryDropoffCurveShortDistanceEnd = 4000,
                            PrimaryDropoffCurveMediumDistanceAdjustment = 4000,
                            PrimaryDropoffCurveMediumDistanceStart = 4000,
                            PrimaryDropoffCurveMediumDistanceEnd = 4000,
                            PrimaryDropoffCurveLongDistanceAdjustment = 4000,
                            PrimaryDropoffCurveLongDistanceStart = 4000,
                            PrimaryDropoffCurveLongDistanceEnd = 4000,
                            PrimaryDropoffCurveLongevity = 1500,
                            PrimaryDropoffCurveLongevityAdjustment = -1,
                            SecondaryReturnDivisor = 100,
                            FinalReturnDivisor = 500,
                            SecondaryDropoffCurveOffset = 0,
                            SecondaryDropoffCurveDistanceAdjustment = 4000,
                            SecondaryDropoffCurveLongevity = 150,
                            SecondaryDropoffCurveLongevityAdjustment = 4000,
                        },
                        new BulkCargoDefinition {
                            ItemID = 12,
                            TypeName = "Paper",
                            CargoLabel = "PAPR",
                            PriceFactor = 72,
                            Color = Colors.LightGreen,
                            CargoSprite = "0x10D9",
                            CargoIcon = "",
                            MaxDistance = 4000,
                            DiminishingReturnsLinearity = 1000,
                            MaxDeliveryTime = 256,
                            LateCargoDivider = 1,
                        },
                        new PerishableCargoDefinition {
                            ItemID = 13,
                            TypeName = "Fruit",
                            CargoLabel = "FRUT",
                            PriceFactor = 92,
                            Color = Colors.Gold,
                            CargoSprite = "0x10D4",
                            CargoIcon = "",
                            MaxDistance = 4000,
                            DiminishingReturnsLinearity = 1000,
                            PrimaryDropoffCurveOffset = 75,
                            PrimaryDropoffCurveShortDistanceAdjustment = -500,
                            PrimaryDropoffCurveShortDistanceEnd = 4000,
                            PrimaryDropoffCurveMediumDistanceAdjustment = 4000,
                            PrimaryDropoffCurveMediumDistanceStart = 4000,
                            PrimaryDropoffCurveMediumDistanceEnd = 4000,
                            PrimaryDropoffCurveLongDistanceAdjustment = 4000,
                            PrimaryDropoffCurveLongDistanceStart = 4000,
                            PrimaryDropoffCurveLongDistanceEnd = 4000,
                            PrimaryDropoffCurveLongevity = 1500,
                            PrimaryDropoffCurveLongevityAdjustment = -1,
                            SecondaryReturnDivisor = 100,
                            FinalReturnDivisor = 500,
                            SecondaryDropoffCurveOffset = 0,
                            SecondaryDropoffCurveDistanceAdjustment = 4000,
                            SecondaryDropoffCurveLongevity = 150,
                            SecondaryDropoffCurveLongevityAdjustment = 4000,
                        },
                        new PerishableCargoDefinition {
                            ItemID = 14,
                            TypeName = "Fish",
                            CargoLabel = "FISH",
                            PriceFactor = 68,
                            Color = Color.FromRgb(0xD0, 0xD0, 0x50),
                            CargoSprite = "NEW_CARGO_SPRITE",
                            CargoIcon = "cargoicon_fish",
                            MaxDistance = 4000,
                            DiminishingReturnsLinearity = 1000,
                            PrimaryDropoffCurveOffset = 180,
                            PrimaryDropoffCurveShortDistanceAdjustment = -500,
                            PrimaryDropoffCurveShortDistanceEnd = 4000,
                            PrimaryDropoffCurveMediumDistanceAdjustment = 4000,
                            PrimaryDropoffCurveMediumDistanceStart = 4000,
                            PrimaryDropoffCurveMediumDistanceEnd = 4000,
                            PrimaryDropoffCurveLongDistanceAdjustment = 4000,
                            PrimaryDropoffCurveLongDistanceStart = 4000,
                            PrimaryDropoffCurveLongDistanceEnd = 4000,
                            PrimaryDropoffCurveLongevity = 1500,
                            PrimaryDropoffCurveLongevityAdjustment = -1,
                            SecondaryReturnDivisor = 100,
                            FinalReturnDivisor = 500,
                            SecondaryDropoffCurveOffset = 0,
                            SecondaryDropoffCurveDistanceAdjustment = 4000,
                            SecondaryDropoffCurveLongevity = 150,
                            SecondaryDropoffCurveLongevityAdjustment = 4000,
                        },
                        new BulkCargoDefinition {
                            ItemID = 15,
                            TypeName = "Wool",
                            CargoLabel = "WOOL",
                            PriceFactor = 79,
                            Color = Color.FromRgb(0xF0, 0xF0, 0x80),
                            CargoSprite = "NEW_CARGO_SPRITE",
                            CargoIcon = "cargoicon_wool",
                            MaxDistance = 4000,
                            DiminishingReturnsLinearity = 1000,
                            MaxDeliveryTime = 256,
                            LateCargoDivider = 1,
                        },
                        // 16 is null
                        new BulkCargoDefinition {
                            ItemID = 17,
                            TypeName = "Sand",
                            CargoLabel = "SAND",
                            PriceFactor = 55,
                            Color = Colors.Green,
                            CargoSprite = "NEW_CARGO_SPRITE",
                            CargoIcon = "cargoicon_sand",
                            MaxDistance = 4000,
                            DiminishingReturnsLinearity = 1000,
                            MaxDeliveryTime = 256,
                            LateCargoDivider = 1,
                        },
                        new BulkCargoDefinition {
                            ItemID = 18,
                            TypeName = "Glass",
                            CargoLabel = "GLAS",
                            PriceFactor = 88,
                            Color = Colors.SkyBlue,
                            CargoSprite = "NEW_CARGO_SPRITE",
                            CargoIcon = "cargoicon_glass",
                            MaxDistance = 4000,
                            DiminishingReturnsLinearity = 1000,
                            MaxDeliveryTime = 256,
                            LateCargoDivider = 1,
                        },
                        new BulkCargoDefinition {
                            ItemID = 19,
                            TypeName = "Wood products",
                            CargoLabel = "WDPR",
                            PriceFactor = 77,
                            Color = Colors.LightGreen,
                            CargoSprite = "NEW_CARGO_SPRITE",
                            CargoIcon = "cargoicon_wood_products",
                            MaxDistance = 4000,
                            DiminishingReturnsLinearity = 1000,
                            MaxDeliveryTime = 256,
                            LateCargoDivider = 1,
                        },
                        new BulkCargoDefinition {
                            ItemID = 20,
                            TypeName = "Dyes",
                            CargoLabel = "DYES",
                            PriceFactor = 83,
                            Color = Colors.Violet,
                            CargoSprite = "NEW_CARGO_SPRITE",
                            CargoIcon = "cargoicon_dyes",
                            MaxDistance = 4000,
                            DiminishingReturnsLinearity = 1000,
                            MaxDeliveryTime = 256,
                            LateCargoDivider = 1,
                        },
                        new BulkCargoDefinition {
                            ItemID = 21,
                            TypeName = "Fertilizer",
                            CargoLabel = "FERT",
                            PriceFactor = 69,
                            Color = Colors.SlateGray,
                            CargoSprite = "NEW_CARGO_SPRITE",
                            CargoIcon = "cargoicon_fertilizer",
                            MaxDistance = 4000,
                            DiminishingReturnsLinearity = 1000,
                            MaxDeliveryTime = 256,
                            LateCargoDivider = 1,
                        },
                        new BulkCargoDefinition {
                            ItemID = 22,
                            TypeName = "Oil seeds",
                            CargoLabel = "OLSD",
                            PriceFactor = 78,
                            Color = Colors.SandyBrown,
                            CargoSprite = "NEW_CARGO_SPRITE",
                            CargoIcon = "cargoicon_oil_seeds",
                            MaxDistance = 4000,
                            DiminishingReturnsLinearity = 1000,
                            MaxDeliveryTime = 256,
                            LateCargoDivider = 1,
                        },
                        new BulkCargoDefinition {
                            ItemID = 23,
                            TypeName = "Refined products",
                            CargoLabel = "RFPR",
                            PriceFactor = 92,
                            Color = Color.FromRgb(0x90, 0x40, 0xA0),
                            CargoSprite = "NEW_CARGO_SPRITE",
                            CargoIcon = "cargoicon_refined_products",
                            MaxDistance = 4000,
                            DiminishingReturnsLinearity = 1000,
                            MaxDeliveryTime = 256,
                            LateCargoDivider = 1,
                        },
                        new BulkCargoDefinition {
                            ItemID = 24,
                            TypeName = "Vehicles",
                            CargoLabel = "VEHI",
                            PriceFactor = 165,
                            Color = Color.FromRgb(0xFF, 0xC0, 0x50),
                            CargoSprite = "NEW_CARGO_SPRITE",
                            CargoIcon = "cargoicon_vehicles",
                            MaxDistance = 4000,
                            DiminishingReturnsLinearity = 1000,
                            MaxDeliveryTime = 256,
                            LateCargoDivider = 1,
                        },
                        new BulkCargoDefinition {
                            ItemID = 25,
                            TypeName = "Petrol",
                            CargoLabel = "PETR",
                            PriceFactor = 102,
                            Color = Color.FromRgb(0xA0, 0x60, 0xB0),
                            CargoSprite = "NEW_CARGO_SPRITE",
                            CargoIcon = "cargoicon_petrol",
                            MaxDistance = 4000,
                            DiminishingReturnsLinearity = 1000,
                            MaxDeliveryTime = 256,
                            LateCargoDivider = 1,
                        },
                        new BulkCargoDefinition {
                            ItemID = 26,
                            TypeName = "Bauxite",
                            CargoLabel = "AORE",
                            PriceFactor = 66,
                            Color = Colors.DarkRed,
                            CargoSprite = "0x10D1",
                            CargoIcon = "",
                            MaxDistance = 4000,
                            DiminishingReturnsLinearity = 1000,
                            MaxDeliveryTime = 256,
                            LateCargoDivider = 1,
                        },
                        new BulkCargoDefinition {
                            ItemID = 27,
                            TypeName = "Water",
                            CargoLabel = "WATR",
                            PriceFactor = 51,
                            Color = Colors.Navy,
                            CargoSprite = "0x10D6",
                            CargoIcon = "",
                            MaxDistance = 4000,
                            DiminishingReturnsLinearity = 1000,
                            MaxDeliveryTime = 256,
                            LateCargoDivider = 1,
                        },
                        new BulkCargoDefinition {
                            ItemID = 28,
                            TypeName = "Building materials",
                            CargoLabel = "BDMT",
                            PriceFactor = 94,
                            Color = Colors.Silver,
                            CargoSprite = "NEW_CARGO_SPRITE",
                            CargoIcon = "cargoicon_building_materials",
                            MaxDistance = 4000,
                            DiminishingReturnsLinearity = 1000,
                            MaxDeliveryTime = 256,
                            LateCargoDivider = 1,
                        },
                        new BulkCargoDefinition {
                            ItemID = 29,
                            TypeName = "Fiber crops",
                            CargoLabel = "FICR",
                            PriceFactor = 67,
                            Color = Colors.Orange,
                            CargoSprite = "NEW_CARGO_SPRITE",
                            CargoIcon = "cargoicon_fibre_crops",
                            MaxDistance = 4000,
                            DiminishingReturnsLinearity = 1000,
                            MaxDeliveryTime = 256,
                            LateCargoDivider = 1,
                        },
                        // 30 is null
                        new PerishableCargoDefinition {
                            ItemID = 31,
                            TypeName = "Tourists",
                            CargoLabel = "TOUR",
                            PriceFactor = 145,
                            Color = Colors.Black,
                            CargoSprite = "NEW_CARGO_SPRITE",
                            CargoIcon = "cargoicon_tourists",
                            MaxDistance = 4000,
                            DiminishingReturnsLinearity = 1000,
                            PrimaryDropoffCurveOffset = 8,
                            PrimaryDropoffCurveShortDistanceAdjustment = 6,
                            PrimaryDropoffCurveShortDistanceEnd = 300,
                            PrimaryDropoffCurveMediumDistanceAdjustment = 12,
                            PrimaryDropoffCurveMediumDistanceStart = 300,
                            PrimaryDropoffCurveMediumDistanceEnd = 500,
                            PrimaryDropoffCurveLongDistanceAdjustment = -12,
                            PrimaryDropoffCurveLongDistanceStart = 500,
                            PrimaryDropoffCurveLongDistanceEnd = 1000,
                            PrimaryDropoffCurveLongevity = 750,
                            PrimaryDropoffCurveLongevityAdjustment = 20,
                            SecondaryReturnDivisor = 4,
                            FinalReturnDivisor = 16,
                            SecondaryDropoffCurveOffset = 150,
                            SecondaryDropoffCurveDistanceAdjustment = -15,
                            SecondaryDropoffCurveLongevity = 800,
                            SecondaryDropoffCurveLongevityAdjustment = 20,
                        }
                    }
                }
            };

        public static CargoScheme GetSchemeByName(string schemeName) {
            return Defaults.Find(scheme => scheme.SchemeName == schemeName);
        }
    }
}
